force-app/main/default/objects/Account/fields/BI_Enrichment_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BI_Enrichment_Sync_Status__c</fullName>
    <description>SFDC-3629 Flag for error recovery related to BI enrichment</description>
    <label>BI Enrichment Sync Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success - segment</fullName>
            </value>
            <value>
                <fullName>Failed - segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Charm_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Charm_Revenue__c</fullName>
    <description>Guess at brand&apos;s revenue</description>
    <inlineHelpText>Guess at brand&apos;s revenue</inlineHelpText>
    <label>Charm Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country Indicated by Rep</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entrepreneur</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
                <isActive>false</isActive>
                <label>Enterprise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Business_Name__c</fullName>
    <description>Complete Legal Name of account used for Compliance
Populated by the Partner Application form
JIRA SFDC-527</description>
    <label>Legal Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Segmentation_Sync_Ready__c.field-meta.xml
<CustomField>
    <fullName>Segmentation_Sync_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFDC-3627 Indicates record is ready for segmentation sync</description>
    <label>Segmentation Sync Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreLeads_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>StoreLeads_Annual_Revenue__c</fullName>
    <description>The store&apos;s estimated yearly sales (based on traffic estimates to the store&apos;s ecommerce website). Values in USD dollars.</description>
    <inlineHelpText>The store&apos;s estimated yearly sales (based on traffic estimates to the store&apos;s ecommerce website). Values in USD dollars.</inlineHelpText>
    <label>StoreLeads Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BIEnrichmentTest.cls
//[RGaokar 11/07/2023 SFDC-3627 Send Salesforce Account/Lead Info to BI Model]
@isTest
public class BIEnrichmentTest {
    @testSetup
    static void dataSetup(){
        //Create accounts
        List<account> accList = new List<account>();
        accList.add(new Account(Name='Test Account 1', Product_Klaviyo_Account_ID__c = '1212', Website = 'test1@test.com', 
                                Country__c = 'USA', Legal_Business_Name__c = 'test1', Charm_Revenue__c = 100,
                                StoreLeads_Annual_Revenue__c = 100));
        
        accList.add(new Account(Name='Test Account 2', Product_Klaviyo_Account_ID__c = '2323', Website = 'test2@test.com', 
                                Country__c = 'USA', Legal_Business_Name__c = 'test2', Charm_Revenue__c = 200,
                                StoreLeads_Annual_Revenue__c = 200));
        
        insert accList;
        
        //Create Leads
        List<lead> leadList = new List<lead>();
        leadList.add(new lead(LastName='Test Lead 1', Website = 'test1@test.com', Country_Location__c = 'USA', 
                              Company = 'test1', Charm_Revenue__c = 100,StoreLeads_Annual_Revenue__c = 100,
                              BI_Enrichment_Sync_Status__c = 'Success - segment'));
        
        leadList.add(new lead(LastName='Test Lead 2', Website = 'test2@test.com', Country_Location__c = 'USA', 
                              Company = 'test2', Charm_Revenue__c = 200,StoreLeads_Annual_Revenue__c = 200));
        
        insert leadList;   
    }
    
    @isTest
    static void testAccountBISync(){
        List<account> accList = [Select id,Website,Country__c,Legal_Business_Name__c,Charm_Revenue__c,
                                 StoreLeads_Annual_Revenue__c,BI_Enrichment_Sync_Status__c from Account];
        
        List<BIEnrichmentProcessor.recordWrapper>records = new List<BIEnrichmentProcessor.recordWrapper>();
        for(account a:accList){
            BIEnrichmentProcessor.recordWrapper record = new BIEnrichmentProcessor.recordWrapper();
            record.recordId = a.Id;
            record.processingType = 'segment';
            records.add(record);
        }
        
        Test.startTest();
        BIEnrichmentProcessor.getRecords(records);
        Test.stopTest();
    }
    
    @isTest
    static void testLeadBISync(){
        List<lead> leadList = [Select id,LastName,Website,Country_Location__c,Company,Charm_Revenue__c,
                               StoreLeads_Annual_Revenue__c,BI_Enrichment_Sync_Status__c from lead];
        List<BIEnrichmentProcessor.recordWrapper>records = new List<BIEnrichmentProcessor.recordWrapper>();
        for(lead l:leadList){
            BIEnrichmentProcessor.recordWrapper record = new BIEnrichmentProcessor.recordWrapper();
            record.recordId = l.Id;
            record.processingType = 'segment';
            records.add(record);
        }
        
        Test.startTest();
        BIEnrichmentProcessor.getRecords(records);
        Test.stopTest();
    }
    
    @isTest
    static void testAccountBIErrorSync(){
        List<account> accList = [Select id,Website,Country__c,Legal_Business_Name__c,Charm_Revenue__c,
                                 StoreLeads_Annual_Revenue__c,BI_Enrichment_Sync_Status__c,
                                 Segmentation_Sync_Ready__c,Customer_Group__c from Account];
        accList[0].BI_Enrichment_Sync_Status__c = 'Failed - segment';
        accList[1].Segmentation_Sync_Ready__c = true;
        update accList;
        
        Test.startTest();
        BIEnrichmentErrorRecoveryScheduler biEnrichSch = new BIEnrichmentErrorRecoveryScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test BI Enrich Error Recovery Scheduler', sch, biEnrichSch);
        Test.stopTest();
    }
    
    @isTest
    static void testLeadBIErrorSync(){
        List<lead> leadList = [Select id,LastName,Website,Country_Location__c,Company,Charm_Revenue__c,
                               StoreLeads_Annual_Revenue__c,BI_Enrichment_Sync_Status__c,
                               Segmentation_Sync_Ready__c,Customer_Group__c from lead];
        leadList[0].BI_Enrichment_Sync_Status__c = 'Failed - segment';
        leadList[1].Segmentation_Sync_Ready__c = true;
        update leadList;
        
        Test.startTest();
        BIEnrichmentErrorRecoveryScheduler biEnrichSch = new BIEnrichmentErrorRecoveryScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test BI Enrich Error Recovery Scheduler', sch, biEnrichSch);
        Test.stopTest();
    }
}