force-app/main/default/objects/Account/fields/Calculated_Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Last_Activity_Date__c</fullName>
    <formula>IF(

AND(
 NOT( ISBLANK( LastActivityDate )),
 NOT( ISBLANK( Last_Activity_Date_Custom__c )),
Last_Activity_Date_Custom__c &gt;= LastActivityDate
),

Last_Activity_Date_Custom__c, 

IF(

AND(
 NOT( ISBLANK( LastActivityDate )),
 NOT( ISBLANK( Last_Activity_Date_Custom__c )),
LastActivityDate &gt; Last_Activity_Date_Custom__c
),

LastActivityDate,

IF(

 NOT( ISBLANK( LastActivityDate )),

LastActivityDate,

IF(

 NOT( ISBLANK( Last_Activity_Date_Custom__c )),

Last_Activity_Date_Custom__c,

NULL

)

)

)

)</formula>
    <label>Calculated Last Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <inlineHelpText>Roll-Up Summary that outputs the Close Date of the most recent Closed Won Opportunity with an Opportunity Type Bucket Name containing “Cancellation”.</inlineHelpText>
    <label>Most Recent Cancellation Date</label>
    <summarizedField>Opportunity.CloseDate</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.of_Churn_MRR__c</field>
        <operation>lessThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Competitor_with_Current_Contract__c.field-meta.xml
<CustomField>
    <fullName>Competitor_with_Current_Contract__c</fullName>
    <label>Competitor with Current Contract</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Contract_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Contract_Expiration_Date__c</fullName>
    <description>The date in which an Accounts contract with an email provider expires</description>
    <inlineHelpText>The date in which an Accounts contract with an email provider expires</inlineHelpText>
    <label>Email Competitor Contract Exp. Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FM_Compiled_Ecommerce_Platform__c.field-meta.xml
<CustomField>
    <fullName>FM_Compiled_Ecommerce_Platform__c</fullName>
    <formula>IF(ISPICKVAL(Klaviyo_Product_Usage__r.Ecommerce_Platform__c,&quot;&quot;),
IF(
ISPICKVAL(Klaviyo_Product_Usage__r.PRODUCT_WizardDeclaredEcommercePlatform__c,&quot;Custom Ecommerce Integration&quot;),&quot;Custom&quot;,
IF(
AND(
ISPICKVAL(Klaviyo_Product_Usage__r.PRODUCT_Ecommerce_Integration__c,&quot;&quot;),
NOT(ISPICKVAL(Ecommerce_Platform__c,&quot;&quot;))
),
TEXT(Ecommerce_Platform__c),
IF(
ISPICKVAL(Klaviyo_Product_Usage__r.PRODUCT_Ecommerce_Integration__c,&quot;&quot;),
&quot;No Active Ecommerce Integration&quot;,
IF(
AND(
ISPICKVAL(Klaviyo_Product_Usage__r.PRODUCT_Shopify_Plan__c,&quot;shopify_plus&quot;),
ISPICKVAL(Klaviyo_Product_Usage__r.PRODUCT_Ecommerce_Integration__c,&quot;shopify&quot;)),
&quot;Shopify Plus&quot;,TEXT(Klaviyo_Product_Usage__r.PRODUCT_Ecommerce_Integration__c))))),
TEXT(Klaviyo_Product_Usage__r.Ecommerce_Platform__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Compiled Ecommerce Platform</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Activity_Date_Custom__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date_Custom__c</fullName>
    <inlineHelpText>This Last Activity Date is pulled from the custom Activities object to capture activity on the Lead object as well</inlineHelpText>
    <label>Last Activity Date (Custom)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Owner_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Owner_Change_Date__c</fullName>
    <label>Last Owner Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/MRRCalc__c.field-meta.xml
<CustomField>
    <fullName>MRRCalc__c</fullName>
    <inlineHelpText>The sum of all Closed Won Opportunity MRR associated with this SF account.</inlineHelpText>
    <label>MRR</label>
    <summarizedField>Opportunity.MRR__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Type__c</field>
        <operation>notEqual</operation>
        <value>Initial Transaction, Subsequent Transaction</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/RU_of_Open_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>RU_of_Open_Opportunities__c</fullName>
    <inlineHelpText>Number of Open Opportunities associated with this Account. Calculated with the Rollup COUNT field.</inlineHelpText>
    <label># of Open Opportunities</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>&lt;NEEDS RESOLUTION&gt;, Sales Accepted Opportunity, Best Case, Most Likely, Commit, Not Forecastable Opportunity</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Closed Won, Closed Lost, Closed Won - Needs Review</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Opportunity_Product__c</field>
        <operation>notEqual</operation>
        <value>Toll Free Number Subscription, Complimentary Long Number Subscription, Long Number Subscription, Short Code Subscription, Short Code Throughput Increase Subscription, Toll Free Number Throughput Increase Subscription, SMS Funds</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Target_Account_Status__c</fullName>
    <inlineHelpText>What is the current status of your engagement with this Target Account?</inlineHelpText>
    <label>Target Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target_Account_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Untouched_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Untouched_Status_Change__c</fullName>
    <label>Untouched Status Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TargetAccountStatusBatch.cls
/*
For Accounts WHERE: MRRCalc__c = 0 AND RecordTypeId = '012d0000001YZJK' AND FINANCE_Payment_Method__c = 'Stripe' ﻿AND ﻿Parent is null AND Account Owner != Salesforce API, Core Placeholder, Special Ops Placeholder, or Klaviyo Partners
AND RU_of_Open_Opportunities__c = 0 AND (TODAY - Calculated_Last_Activity_Date__c) > 30 AND (TODAY - Last_Owner_Change_Date__c) > 5 AND FM_Compiled_Ecommerce_Platform__c CONTAINS 'shopify' (not case sensitive)
* AND 31 (or more) ﻿days since calculated last activity date. If no calculated last activity date, 31 (or more) days since last owner change date. If no last owner change date, 31 days (or more) since created date.

Then:
Target_Account_Status__c = Untouched/Cold
Account Owner = Core Placeholder
Untouched Status Change = Date Stamp

For Accounts WHERE:MRRCalc__c = 0 AND RecordTypeId = '012d0000001YZJK' AND FINANCE_Payment_Method__c = 'Stripe' ﻿﻿AND ﻿Parent is null AND Account Owner != Salesforce API, Core Placeholder, Special Ops Placeholder, or Klaviyo Partners
AND RU_of_Open_Opportunities__c = 0 AND (TODAY - Calculated_Last_Activity_Date__c) > 30 AND (TODAY - Last_Owner_Change_Date__c) > 5 AND FM_Compiled_Ecommerce_Platform__c DOES NOT CONTAIN 'shopify' (not case sensitive)
* AND 31 (or more) ﻿days since calculated last activity date. If no calculated last activity date, 31 (or more) days since last owner change date. If no last owner change date, 31 days (or more) since created date.

Then:
Target_Account_Status__c = Untouched/Cold
Account Owner = Special Ops Placeholder
Untouched Status Change = Date Stamp

For Accounts WHERE: MRRCalc__c = 0 AND RecordTypeId = '012d0000001YZJK' AND FINANCE_Payment_Method__c = 'Stripe' AND Account Owner != Salesforce API, Core Placeholder, Special Ops Placeholder, or Klaviyo Partners
Target_Account_Status__c = Untouched/Cold
AND RU_of_Open_Opportunities__c = 0 AND (TODAY - Calculated_Last_Activity_Date__c) <= 30
*AND Calculated Last Activity Date is within last 31 days (if null, does not meet criteria)

Then: 
Target_Account_Status__c = Attempting
*/

global class TargetAccountStatusBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    public Set<Id> userIds = new Set<id>(); 
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        List<Id> userList = new List<Id>();
        userList.add(System.Label.Salesforce_API_User_Id);
        userList.add(System.Label.Core_Placeholder_Id);
        userList.add(System.Label.Special_Ops_Placeholder_Id);
        userList.add(System.Label.Klaviyo_Partners_Id);
         
        List<User> userExceptionList = [SELECT Id FROM User Where Target_Account_Exception__c = true];
    
        String query = 'SELECT Id, Name, MRRCalc__c, RecordTypeId, FINANCE_Payment_Method__c, OwnerId, Target_Account_Status__c, RU_of_Open_Opportunities__c, Calculated_Last_Activity_Date__c, LastActivityDate, Last_Activity_Date_Custom__c, Parent.Name, Last_Owner_Change_Date__c, CreatedDate, FM_Compiled_Ecommerce_Platform__c, Current_Contract_Expiration_Date__c, Competitor_with_Current_Contract__c, Cancellation_Date__c FROM Account where  MRRCalc__c = 0 AND RecordTypeId = \'012d0000001YZJK\' AND FINANCE_Payment_Method__c = \'Stripe\' AND RU_of_Open_Opportunities__c = 0 AND ParentId = null AND OwnerId NOT in: userList AND OwnerId NOT in: userExceptionList';
        return Database.getQueryLocator(query);   
         
    }
    
    global void execute(Database.BatchableContext bc, List<Account> accts){
        
        KlaviyoAccountSync.isRunFromTAPBatch = true;
        
        for(Account acct: accts){
            if(acct.Target_Account_Status__c == 'Untouched' && acct.Calculated_Last_Activity_Date__c <> null && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) <= 31)
            { 
                acct.Target_Account_Status__c = 'Attempting';
                update acct;
            }
            // [SFDC-2833 VRajapatruni 06/20/2023] Target account Status is not Churned OR (Target account Status IS 'Churned' AND churn date was more than 12 months ago') 
            if(acct.Current_Contract_Expiration_Date__c == null && (acct.Target_Account_Status__c <> 'Churned' || (acct.Target_Account_Status__c == 'Churned' && acct.Cancellation_Date__c != null && acct.Cancellation_Date__c.addMonths(12) < Date.today()))){            
                if((((acct.Last_Owner_Change_Date__c <> null && acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c > acct.Calculated_Last_Activity_Date__c && acct.Last_Owner_Change_Date__c.daysBetween(Date.today()) > 5)
                            || (acct.Calculated_Last_Activity_Date__c == null && acct.Last_Owner_Change_Date__c <> null && acct.Last_Owner_Change_Date__c.daysBetween(Date.today()) > 5))
                        ||((acct.Last_Owner_Change_Date__c <> null && acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c < acct.Calculated_Last_Activity_Date__c && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) > 30)
                            || (acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c == null && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) > 30))
                        ||(acct.Calculated_Last_Activity_Date__c == null && acct.Last_Owner_Change_Date__c == null && acct.CreatedDate <> null && acct.CreatedDate.date().daysBetween(Date.today()) > 5)
                        ||(acct.Last_Owner_Change_Date__c <> null && acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c == acct.Calculated_Last_Activity_Date__c && acct.Last_Owner_Change_Date__c.daysBetween(Date.today()) > 5 && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) > 30)) //[SFDC-1297 VR] Bug fix when both dates are same 
                        
                    && (acct.FM_Compiled_Ecommerce_Platform__c <> null && acct.FM_Compiled_Ecommerce_Platform__c.containsIgnoreCase('shopify')))
                 {  
                    userIds.add(acct.OwnerId);
                    acct.Target_Account_Status__c = 'Untouched';
                    acct.ownerId = System.Label.Core_Placeholder_Id; 
                    acct.Untouched_Status_Change__c = date.today();
                    update acct;
                 }
                    
                 if((((acct.Last_Owner_Change_Date__c <> null && acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c > acct.Calculated_Last_Activity_Date__c && acct.Last_Owner_Change_Date__c.daysBetween(Date.today()) > 5)
                            || (acct.Calculated_Last_Activity_Date__c == null && acct.Last_Owner_Change_Date__c <> null && acct.Last_Owner_Change_Date__c.daysBetween(Date.today()) > 5))
                        ||((acct.Last_Owner_Change_Date__c <> null && acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c < acct.Calculated_Last_Activity_Date__c && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) > 30)
                            || (acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c == null && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) > 30))
                        ||(acct.Calculated_Last_Activity_Date__c == null && acct.Last_Owner_Change_Date__c == null && acct.CreatedDate <> null && acct.CreatedDate.date().daysBetween(Date.today()) > 5)
                        ||(acct.Last_Owner_Change_Date__c <> null && acct.Calculated_Last_Activity_Date__c <> null && acct.Last_Owner_Change_Date__c == acct.Calculated_Last_Activity_Date__c && acct.Last_Owner_Change_Date__c.daysBetween(Date.today()) > 5 && acct.Calculated_Last_Activity_Date__c.daysBetween(Date.today()) > 30)) //[SFDC-1297 VR] Bug fix when both dates are same 
                    
                    && (acct.FM_Compiled_Ecommerce_Platform__c == null || (!acct.FM_Compiled_Ecommerce_Platform__c.containsIgnoreCase('shopify'))))
                 { 
                    userIds.add(acct.OwnerId);
                    acct.Target_Account_Status__c = 'Untouched';
                    acct.ownerId = System.Label.Special_Ops_Placeholder_Id; 
                    acct.Untouched_Status_Change__c = date.today();
                    update acct;
                 }
            } 
        }     
        
    }    
    
    global void finish(Database.BatchableContext bc){
        
        if(!userIds.isEmpty() && !Test.isRunningTest()){
            Database.executeBatch(new UpdateAssociatedAccountsBatch(userIds), 1);
        }
        
    }  
      
}