force-app/main/default/objects/Account/fields/Channel_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the Channel Manager assigned to this Referral Partner</inlineHelpText>
    <label>Partner Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OBS who onboarded customer</description>
    <label>Onboarding Specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KlaviyoAccountSyncTest.cls
@isTest
private class KlaviyoAccountSyncTest {
    /** Tests the KlaviyoAccountSync APEX class as well as trigger. */
    static testMethod void testSyncAccountManager() {
        /** Test that the KlaviyoAccountSync class's syncAccountManager method works. */
        Test.startTest();
        List<User> users = [SELECT Id FROM User WHERE userType='Standard' LIMIT 1];
        Id userId = users.get(0).Id;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User usr = new User(Id = userId,
                            LastName = 'person',
                            FirstName='Test',
                            Alias = 'tperson',
                            Email = 'test.person@email.com',
                            Username = 'test.person@email.com',
                            ProfileId = p.Id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        Account acct = new Account(Name='### Test Account ###',
                                      Product_Klaviyo_Account_ID__c = 'abc123');
        // Set new fields
        acct.Channel_Manager__c = usr.Id;
        acct.OwnerId = usr.Id;
        acct.Onboarding_Specialist__c = usr.Id;
        acct.SUPPORT_Account_Manager__c = usr.Id;
        // Queue Account for processing
		Set<Account> accountsToSync = new Set<Account>();
        accountsToSync.add(acct);
        KlaviyoAccountSync klAccountSync = new KlaviyoAccountSync(accountsToSync);
        ID jobID = System.enqueueJob(klAccountSync);
        System.debug('Queued new job with jobID' + jobID);

        Test.stopTest();
    }

    static testMethod void testAccountTrigger() {
        /** Test the trigger on an Account for insert & update runs successfully. */
        Test.startTest();

        List<User> users = [SELECT Id FROM User WHERE userType='Standard' LIMIT 1];
        Id userId = users.get(0).Id;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User usr = new User(Id = userId,
                            LastName = 'person',
                            FirstName='Test',
                            Alias = 'tperson',
                            Email = 'test.person@email.com',
                            Username = 'test.person@email.com',
                            ProfileId = p.Id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        
        Account acct = new Account(Name='### Test Account ###',
                                      Product_Klaviyo_Account_ID__c = 'abc123');
        // Set new account Owner
        acct.OwnerId = usr.Id;
        acct.Onboarding_Specialist__c = usr.Id;
        insert acct;
        // Set new CSM
        acct.Channel_Manager__c = usr.Id;
        update acct;

        Test.stopTest();
    }
}