force-app/main/default/objects/Account/fields/Clean_Website__c.field-meta.xml
<CustomField>
    <fullName>Clean_Website__c</fullName>
    <formula>IF($Setup.PWR_Phase_1_Custom_Setting__c.Is_Active__c, Deduplicated_Account_Website__c,
SUBSTITUTE(
    IF(
        FIND(&quot;/&quot;,
            IF(
                FIND(&quot;www.&quot;, Website) &gt; 0,
                IF(
                    FIND(&quot;//&quot;, Website) &gt; 0,
                    SUBSTITUTE(
                               Website,
                               LEFT(
                                    Website,
                                    FIND(&quot;//www.&quot;, Website) + 5),
                               NULL
                               ),
                    Website
                 ),
                 IF(
                     FIND(&quot;//&quot;, Website) &gt; 0,
                     SUBSTITUTE(
                         Website,
                         LEFT(
                             Website,
                             FIND(&quot;//&quot;, Website) + 1),
                         NULL),
                     Website
                     )
                 )
             ) &gt; 0,
        LEFT(
            IF(
                FIND(&quot;www.&quot;,Website)&gt;0,
                IF(
                    FIND(&quot;//&quot;,Website)&gt;0,
                    SUBSTITUTE(
                        Website,
                        LEFT(
                            Website,
                            FIND(&quot;//www.&quot;,Website) + 5
                        ),
                       NULL),
                    Website
                ),
                IF(
                    FIND(&quot;//&quot;,Website)&gt;0,
                    SUBSTITUTE(
                        Website,
                        LEFT(
                            Website,
                            FIND(&quot;//&quot;,Website) + 1
                        ),
                        NULL
                    ),
                    Website
                )
            ),
            FIND(&quot;/&quot;,
                IF(
                    FIND(&quot;www.&quot;,Website)&gt;0,
                    IF(
                        FIND(&quot;//&quot;,Website)&gt;0,
                        SUBSTITUTE(
                            Website,
                            LEFT(
                                Website,
                                FIND(&quot;//www.&quot;, Website) + 5
                            ),
                            NULL
                       ),
                        Website),
                    IF(
                        FIND(&quot;//&quot;,Website) &gt; 0,
                        SUBSTITUTE(
                            Website,
                            LEFT(
                                Website,
                                FIND(&quot;//&quot;,Website) + 1
                            ),
                            NULL
                        ),
                        Website
                    )
                )
            ) -1
        ),
        IF(
            FIND(&quot;www.&quot;,Website)&gt;0,
            IF(
                FIND(&quot;//&quot;,Website)&gt;0,
                SUBSTITUTE(
                    Website,
                    LEFT(
                        Website,
                        FIND(&quot;//www.&quot;,Website)+5),
                    NULL
                ),
                Website
            ),
            IF(
                FIND(&quot;//&quot;,Website)&gt;0,
                SUBSTITUTE(
                    Website,
                    LEFT(
                        Website,
                        FIND(
                             &quot;//&quot;,
                             Website) + 1
                         ),
                        NULL
                ),
                Website)
        )
    ),
    &apos;www.&apos;,
    &apos;&apos;
)
)</formula>
    <label>Clean Website</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Diligent_Search_Failed__c.field-meta.xml
<CustomField>
    <fullName>Diligent_Search_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFDC-1881 Indicates Failed Diligent Search</description>
    <label>Diligent Search Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Business_Name__c</fullName>
    <description>Complete Legal Name of account used for Compliance
Populated by the Partner Application form
JIRA SFDC-527</description>
    <label>Legal Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiligentFailureHandlingBatch.cls
//[RGaokar 3/10/2023 SFDC-2132 Failed Diligent Callout Processing Weekly Job]
public class DiligentFailureHandlingBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    private String query;
    public DiligentFailureHandlingBatch(String query){//Pass the custom query from Anonymous window to run this batch Example: Select id,name,Clean_Website__c,BillingCountry,recordtype.DeveloperName,Legal_Business_Name__c from account where .....
        this.query = query;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        if(this.query == null){
            this.query = 'Select id,name,Clean_Website__c,BillingCountry,recordtype.DeveloperName,Legal_Business_Name__c from account where Diligent_Search_Failed__c = true';
        }
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject>scope){
        List<Account> updatedAccList = new List<Account>();
        List<DiligentSearchProcessor.DiligentPayload>diligentPayloads = new List<DiligentSearchProcessor.DiligentPayload>();
        for(Account a:(List<account>)scope){
            updatedAccList.add(new account(id = a.id, Diligent_Search_Failed__c = false));//reset the failed flag to false
            DiligentSearchProcessor.DiligentPayload payload = new DiligentSearchProcessor.DiligentPayload();
            payload.accountId = a.id;
            payload.country = a.BillingCountry;
            payload.recordType = a.RecordType.DeveloperName;
            if(a.RecordType.DeveloperName == 'Klaviyo_Account'){
                payload.term = a.Clean_Website__c;
            }else if(a.RecordType.DeveloperName == 'Referral_Partner_Account' && string.isNotBlank(a.Legal_Business_Name__c)){
                payload.term = a.Legal_Business_Name__c;
            }else if(a.RecordType.DeveloperName == 'Referral_Partner_Account' && string.isBlank(a.Legal_Business_Name__c)){
                payload.term = a.name;
            }
            diligentPayloads.add(payload);
        }
        
        List<Database.SaveResult> srList = Database.update(updatedAccList, false);
        DiligentSearchProcessor.getDiligentSearchTerms(diligentPayloads);
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
    
}