force-app/main/default/objects/Account/fields/Clean_Website__c.field-meta.xml
<CustomField>
    <fullName>Clean_Website__c</fullName>
    <formula>IF($Setup.PWR_Phase_1_Custom_Setting__c.Is_Active__c, Deduplicated_Account_Website__c,
SUBSTITUTE(
    IF(
        FIND(&quot;/&quot;,
            IF(
                FIND(&quot;www.&quot;, Website) &gt; 0,
                IF(
                    FIND(&quot;//&quot;, Website) &gt; 0,
                    SUBSTITUTE(
                               Website,
                               LEFT(
                                    Website,
                                    FIND(&quot;//www.&quot;, Website) + 5),
                               NULL
                               ),
                    Website
                 ),
                 IF(
                     FIND(&quot;//&quot;, Website) &gt; 0,
                     SUBSTITUTE(
                         Website,
                         LEFT(
                             Website,
                             FIND(&quot;//&quot;, Website) + 1),
                         NULL),
                     Website
                     )
                 )
             ) &gt; 0,
        LEFT(
            IF(
                FIND(&quot;www.&quot;,Website)&gt;0,
                IF(
                    FIND(&quot;//&quot;,Website)&gt;0,
                    SUBSTITUTE(
                        Website,
                        LEFT(
                            Website,
                            FIND(&quot;//www.&quot;,Website) + 5
                        ),
                       NULL),
                    Website
                ),
                IF(
                    FIND(&quot;//&quot;,Website)&gt;0,
                    SUBSTITUTE(
                        Website,
                        LEFT(
                            Website,
                            FIND(&quot;//&quot;,Website) + 1
                        ),
                        NULL
                    ),
                    Website
                )
            ),
            FIND(&quot;/&quot;,
                IF(
                    FIND(&quot;www.&quot;,Website)&gt;0,
                    IF(
                        FIND(&quot;//&quot;,Website)&gt;0,
                        SUBSTITUTE(
                            Website,
                            LEFT(
                                Website,
                                FIND(&quot;//www.&quot;, Website) + 5
                            ),
                            NULL
                       ),
                        Website),
                    IF(
                        FIND(&quot;//&quot;,Website) &gt; 0,
                        SUBSTITUTE(
                            Website,
                            LEFT(
                                Website,
                                FIND(&quot;//&quot;,Website) + 1
                            ),
                            NULL
                        ),
                        Website
                    )
                )
            ) -1
        ),
        IF(
            FIND(&quot;www.&quot;,Website)&gt;0,
            IF(
                FIND(&quot;//&quot;,Website)&gt;0,
                SUBSTITUTE(
                    Website,
                    LEFT(
                        Website,
                        FIND(&quot;//www.&quot;,Website)+5),
                    NULL
                ),
                Website
            ),
            IF(
                FIND(&quot;//&quot;,Website)&gt;0,
                SUBSTITUTE(
                    Website,
                    LEFT(
                        Website,
                        FIND(
                             &quot;//&quot;,
                             Website) + 1
                         ),
                        NULL
                ),
                Website)
        )
    ),
    &apos;www.&apos;,
    &apos;&apos;
)
)</formula>
    <label>Clean Website</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountDeduplicationBatchTest.cls
@isTest
private class AccountDeduplicationBatchTest
{

    @testSetup static void buildData()
    {

        Account Special1 = new Account(Name='Test Account Special1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '11032021', website = 'www.klaviyo.com', FINANCE_Payment_Method__c = 'Wire Transfer / Manual Billing', ParentId = null, RecordTypeId = System.label.Klaviyo_Account_Record_Id);
        Account NotSpecial1 = new Account(Name='Test Account NotSpecial1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = null, website = 'www.klaviyo.com', FINANCE_Payment_Method__c = 'Stripe', ParentId = null, RecordTypeId = System.label.Klaviyo_Account_Record_Id);
        
        Account NotSpecial2 = new Account(Name='Test Account NotSpecial2', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = null, website = 'www.test.com', FINANCE_Payment_Method__c = 'Stripe', ParentId = null, RecordTypeId = System.label.Klaviyo_Account_Record_Id);
        Account NotSpecial3 = new Account(Name='Test Account NotSpecial3', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = null, website = 'www.test.com', FINANCE_Payment_Method__c = 'Stripe', ParentId = null, RecordTypeId = System.label.Klaviyo_Account_Record_Id);
       
        insert new List <Account> {Special1, NotSpecial1, NotSpecial2, NotSpecial3};        
        
    }
    
    @isTest
    private static void testAccountDeduplicationBatch(){
        
        List <Account> lstAccounts = [select Id, Name, Clean_Website__c, Product_Klaviyo_Account_ID__c, ParentId, FINANCE_Payment_Method__c, RecordTypeId from Account order by Name];       
        
        
        Contact con1 = new Contact(FirstName = 'Test', LastName = 'Contact', Phone = '111.111.1111', AccountId = lstAccounts[0].Id);
        insert con1;
        
        con1.AccountId = lstAccounts[1].Id;
        update con1;
        
        Contact con2 = new Contact(FirstName = 'Test', LastName = 'Contact', Phone = '111.111.1111', AccountId = lstAccounts[3].Id);
        insert con2;
        
        con2.AccountId = lstAccounts[2].Id;
        update con2;
        
        Test.StartTest();
        AccountDeduplicationBatchScheduler obj = new AccountDeduplicationBatchScheduler();
        String schedule = '0 0 23 * * ?'; 
        system.schedule('Test Account Deduplication', schedule, obj); 
        
        AccountDeduplicationBatch obj2 = new AccountDeduplicationBatch();
        Database.QueryLocator ql = obj2.start(null);
        obj2.execute(null, lstAccounts);
        obj2.Finish(null);
        
        Test.stopTest();  
                   
    }

}