force-app/main/default/objects/Account/fields/Clean_Website__c.field-meta.xml
<CustomField>
    <fullName>Clean_Website__c</fullName>
    <formula>IF($Setup.PWR_Phase_1_Custom_Setting__c.Is_Active__c, Deduplicated_Account_Website__c,
SUBSTITUTE(
    IF(
        FIND(&quot;/&quot;,
            IF(
                FIND(&quot;www.&quot;, Website) &gt; 0,
                IF(
                    FIND(&quot;//&quot;, Website) &gt; 0,
                    SUBSTITUTE(
                               Website,
                               LEFT(
                                    Website,
                                    FIND(&quot;//www.&quot;, Website) + 5),
                               NULL
                               ),
                    Website
                 ),
                 IF(
                     FIND(&quot;//&quot;, Website) &gt; 0,
                     SUBSTITUTE(
                         Website,
                         LEFT(
                             Website,
                             FIND(&quot;//&quot;, Website) + 1),
                         NULL),
                     Website
                     )
                 )
             ) &gt; 0,
        LEFT(
            IF(
                FIND(&quot;www.&quot;,Website)&gt;0,
                IF(
                    FIND(&quot;//&quot;,Website)&gt;0,
                    SUBSTITUTE(
                        Website,
                        LEFT(
                            Website,
                            FIND(&quot;//www.&quot;,Website) + 5
                        ),
                       NULL),
                    Website
                ),
                IF(
                    FIND(&quot;//&quot;,Website)&gt;0,
                    SUBSTITUTE(
                        Website,
                        LEFT(
                            Website,
                            FIND(&quot;//&quot;,Website) + 1
                        ),
                        NULL
                    ),
                    Website
                )
            ),
            FIND(&quot;/&quot;,
                IF(
                    FIND(&quot;www.&quot;,Website)&gt;0,
                    IF(
                        FIND(&quot;//&quot;,Website)&gt;0,
                        SUBSTITUTE(
                            Website,
                            LEFT(
                                Website,
                                FIND(&quot;//www.&quot;, Website) + 5
                            ),
                            NULL
                       ),
                        Website),
                    IF(
                        FIND(&quot;//&quot;,Website) &gt; 0,
                        SUBSTITUTE(
                            Website,
                            LEFT(
                                Website,
                                FIND(&quot;//&quot;,Website) + 1
                            ),
                            NULL
                        ),
                        Website
                    )
                )
            ) -1
        ),
        IF(
            FIND(&quot;www.&quot;,Website)&gt;0,
            IF(
                FIND(&quot;//&quot;,Website)&gt;0,
                SUBSTITUTE(
                    Website,
                    LEFT(
                        Website,
                        FIND(&quot;//www.&quot;,Website)+5),
                    NULL
                ),
                Website
            ),
            IF(
                FIND(&quot;//&quot;,Website)&gt;0,
                SUBSTITUTE(
                    Website,
                    LEFT(
                        Website,
                        FIND(
                             &quot;//&quot;,
                             Website) + 1
                         ),
                        NULL
                ),
                Website)
        )
    ),
    &apos;www.&apos;,
    &apos;&apos;
)
)</formula>
    <label>Clean Website</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Master_Account_Id__c</fullName>
    <description>This is used for account de-deuplication</description>
    <label>Master Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountDeduplicationCleanBatch.cls
// This class is used to set Master_Account_Id__c to null (used for account deduplication)
// Test class: AccountDeduplicationCleanBatchTest
// To manually execute from dc - Database.executeBatch(new AccountDeduplicationCleanBatch(),10);

global class AccountDeduplicationCleanBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        //Use the below for records when a master account ID already exists
        String allAccounts = 'SELECT Clean_Website__c FROM Account where  RecordType.Name = \'Klaviyo Account\' and Clean_Website__c != null and Clean_Website__c != \'-\' and Clean_Website__c != \'.\' and  Master_Account_Id__c != null';
        return Database.getQueryLocator(allAccounts);
            
    }
    
    global void execute(Database.BatchableContext bc, List<Account> acctRecList){
    
        for(Account a: acctRecList){
            a.Master_Account_Id__c = null;            
        }
        
        if(acctRecList.size() > 0){
            update acctRecList;
        }
        
    }    
    
    global void finish(Database.BatchableContext bc){
        
    }    
}