force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country Indicated by Rep</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Contract_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Contract_Expiration_Date__c</fullName>
    <description>The date in which an Accounts contract with an email provider expires</description>
    <inlineHelpText>The date in which an Accounts contract with an email provider expires</inlineHelpText>
    <label>Email Competitor Contract Exp. Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Email_Platform__c.field-meta.xml
<CustomField>
    <fullName>Current_Email_Platform__c</fullName>
    <label>Current Email Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ecommerce_Platform__c.field-meta.xml
<CustomField>
    <fullName>Ecommerce_Platform__c</fullName>
    <description>replaces the etailinsights field (utilizes its data)</description>
    <label>Ecommerce Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ecommerce_Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Activity_Date_Custom__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date_Custom__c</fullName>
    <inlineHelpText>This Last Activity Date is pulled from the custom Activities object to capture activity on the Lead object as well</inlineHelpText>
    <label>Last Activity Date (Custom)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Owner_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Owner_Change_Date__c</fullName>
    <label>Last Owner Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Medal__c.field-meta.xml
<CustomField>
    <fullName>Medal__c</fullName>
    <description>Tier 1: Platinum
Tier 2: Gold
Tier 3: Bronze + Silver</description>
    <inlineHelpText>Tier 1: Platinum
Tier 2: Gold
Tier 3: Bronze + Silver</inlineHelpText>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>High Opportunity</fullName>
            </value>
            <value>
                <fullName>Longtail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Target_Account_Status__c</fullName>
    <inlineHelpText>What is the current status of your engagement with this Target Account?</inlineHelpText>
    <label>Target Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target_Account_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TargetAccountStatusBatchTest.cls
@isTest
private class TargetAccountStatusBatchTest
{

    @isTest
    private static void testTargetAccountStatusBatch(){
        
        Account a1 = new Account(Name='Test Account A', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1212');
        //a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Klaviyo Account').getRecordTypeId(); 
        a1.FINANCE_Payment_Method__c = 'Stripe';
        a1.RecordTypeId = '012d0000001YZJK';
        a1.Target_Account_Status__c = 'Untouched';
        a1.Current_Email_Platform__c = 'Klaviyo';
        // a1.Ecommerce_Platform__c = 'Shopify';
        a1.Medal__c = 'Tier 1';
        a1.Country__c = 'United States';
        a1.Last_Activity_Date_Custom__c = date.parse('6/30/2020');
        a1.Current_Contract_Expiration_Date__c = null;
        a1.ParentId = null;
        a1.Ecommerce_Platform__c = 'Shopify'; //[SFDC-1297 VR] Added the fields for a1 and a2 to improve code coverage
        
        Account a2 = new Account(Name='Test Account B', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1213');
        a2.FINANCE_Payment_Method__c = 'Stripe';
        a2.RecordTypeId = '012d0000001YZJK';
        a2.Target_Account_Status__c = 'Untouched';
        a2.Current_Email_Platform__c = 'Klaviyo';
        a2.Medal__c = 'Tier 1';
        a2.Country__c = 'United States';
        a2.Last_Activity_Date_Custom__c = date.parse('6/30/2020');
        a2.Last_Owner_Change_Date__c = date.parse('6/30/2020');
        a2.Current_Contract_Expiration_Date__c = null;
        a2.ParentId = null;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator']; 
        UserRole userobj=new UserRole(Name= 'testStampWorkingBDR'); 
        insert userobj; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg888.com', title = 'Product Specialist', UserRoleId = userobj.Id);

        System.runAs(u) {       
            insert new List <Account> {a1, a2}; //[SFDC-1297 VR] Updated a2 
        }
        
        Test.StartTest();
        TargetAccountStatusBatchScheduler obj = new TargetAccountStatusBatchScheduler();
        String schedule = '0 0 23 * * ?'; 
        system.schedule('Test TAP Attempting', schedule, obj); 
        Test.stopTest();  
                   
    }

}