force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country Indicated by Rep</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Email_Platform__c.field-meta.xml
<CustomField>
    <fullName>Current_Email_Platform__c</fullName>
    <label>Current Email Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ecommerce_Platform__c.field-meta.xml
<CustomField>
    <fullName>Ecommerce_Platform__c</fullName>
    <description>replaces the etailinsights field (utilizes its data)</description>
    <label>Ecommerce Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ecommerce_Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Medal__c.field-meta.xml
<CustomField>
    <fullName>Medal__c</fullName>
    <description>Tier 1: Platinum
Tier 2: Gold
Tier 3: Bronze + Silver</description>
    <inlineHelpText>Tier 1: Platinum
Tier 2: Gold
Tier 3: Bronze + Silver</inlineHelpText>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>High Opportunity</fullName>
            </value>
            <value>
                <fullName>Longtail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Target_Account_Status__c</fullName>
    <inlineHelpText>What is the current status of your engagement with this Target Account?</inlineHelpText>
    <label>Target Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target_Account_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TargetAccountDQBatchTest.cls
@isTest
private class TargetAccountDQBatchTest
{
    
    @testSetup static void buildData()
    {

        Account a = new Account(Name='Test Account 1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1212', Target_Account_Status__c = 'Untouched');
        a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Klaviyo Account').getRecordTypeId(); 
        a.FINANCE_Payment_Method__c = 'Stripe';
        a.Current_Email_Platform__c = 'Klaviyo';
        a.Ecommerce_Platform__c = 'Shopify';
        a.Medal__c = 'Tier 1';
        a.Country__c = 'United States'; 
        insert a;
        
        Lead l = new Lead(FirstName = 'Test', LastName = 'Test Last name', Account__c = a.Id, Company = 'Test Company');
        insert l;
        
    }
    
    
    @isTest
    private static void testTargetAccountDQtest(){
    
        List <Account> lstAccounts = [select Id from Account order by Name]; 
        List <Lead> lstLeads = [select Id, isConverted from Lead order by Name]; 
        Set<Id> acctIds = new Set<Id>();
        Set<Id> leadIds = new Set<Id>();
        
        for(Account a : lstAccounts){
            acctIds.add(a.Id);
        }   
        
         for(Lead l : lstLeads){
            if(!l.isConverted)
                {
                    leadIds.add(l.Id);
                }
        }
        
        lstAccounts[0].Target_Account_Status__c = 'DQ - Do not Contact';
        update lstAccounts;
        
        Database.executeBatch(new TargetAccountDQBatch(leadIds, acctIds), 20);
    
    }
    
}