force-app/main/default/objects/Account/fields/Experts_Tier__c.field-meta.xml
<CustomField>
    <fullName>Experts_Tier__c</fullName>
    <description>API name doesn&apos;t match bc of Mike</description>
    <inlineHelpText>Agencies who have an email program and are experts at delivering value with the Klaviyo product for eCommerce brands via setting up/supporting/managing our customers.</inlineHelpText>
    <label>Masters Referral Partner Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Referral_Partner_Tier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Klaviyo_Product_Usage__c.field-meta.xml
<CustomField>
    <fullName>Klaviyo_Product_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Klaviyo Store</label>
    <referenceTo>Klaviyo_Product_Usage__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PRODUCT_Ecommerce_Integration__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_Ecommerce_Integration__c</fullName>
    <label>(Automation Use)Active Ecomm Integration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>shopify</fullName>
            </value>
            <value>
                <fullName>magento</fullName>
            </value>
            <value>
                <fullName>api</fullName>
            </value>
            <value>
                <fullName>bigcommerce</fullName>
            </value>
            <value>
                <fullName>shopdirect</fullName>
            </value>
            <value>
                <fullName>commercev3</fullName>
            </value>
            <value>
                <fullName>spree</fullName>
            </value>
            <value>
                <fullName>volusion</fullName>
            </value>
            <value>
                <fullName>mws</fullName>
            </value>
            <value>
                <fullName>opencart</fullName>
            </value>
            <value>
                <fullName>woocommerce</fullName>
            </value>
            <value>
                <fullName>celery</fullName>
            </value>
            <value>
                <fullName>magento2</fullName>
            </value>
            <value>
                <fullName>three_d_cart</fullName>
            </value>
            <value>
                <fullName>lightspeed</fullName>
            </value>
            <value>
                <fullName>mi_nine</fullName>
            </value>
            <value>
                <fullName>magento_two</fullName>
            </value>
            <value>
                <fullName>stripe</fullName>
            </value>
            <value>
                <fullName>Wix</fullName>
                <label>wix</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PRODUCT_Num_Emailable_Profiles__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_Num_Emailable_Profiles__c</fullName>
    <inlineHelpText>Number of profiles in Klaviyo minus the number of suppressions. This is what we bill customers on.</inlineHelpText>
    <label>(Automation Use) Emailable Profiles</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PRODUCT_Stripe_Net_MRR__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_Stripe_Net_MRR__c</fullName>
    <inlineHelpText>From Stripe: Plan MRR minus any discount.</inlineHelpText>
    <label>(X) Stripe - Net MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SchBatchSyncWithKlaviyoProdUsageTest.cls
/**
 * Name: SchBatchSyncWithKlaviyoProdUsageTest
 * Created on: Jun 2020
 * Created by: J. Pipkin (OpFocus, Inc)
 * Description:
 */

@isTest
public class SchBatchSyncWithKlaviyoProdUsageTest {

    @testSetup static void buildData() {
        //[RGaokar 1/11/2022 TP #95103 KPU Test data to increase code coverage]
        List<Klaviyo_Product_Usage__c> testKPUs = new List<Klaviyo_Product_Usage__c>();
        for(Integer i=0;i<4;i++) {
            testKPUs.add(new Klaviyo_Product_Usage__c(Klaviyo_Account_ID__c = 'TestKPU'+i));
        }
        insert testKPUs;
        
        // To set Updated_By_Heroku__c = true
        for(Klaviyo_Product_Usage__c kpu:testKPUs){
            kpu.PRODUCT_Ecommerce_Integration__c = 'shopify';
            kpu.PRODUCT_Stripe_Net_MRR__c = 100;
            kpu.PRODUCT_of_Emailable_Profiles__c = 3000;
        }
        update testKPUs;
        
        Lead l1 = new Lead(FirstName='Suzie', LastName='Queue', Company='TestCo 1', Klaviyo_Account_ID__c = testKPUs[0].Klaviyo_Account_ID__c);
        insert new List <Lead> {l1};

        // If the TriggerDisablementSwitch has this disabled, enable it for this unit tests so
        // we can cover that code.
        TriggerDisablementSwitchHelper.mapSwitches.put('Klaviyo_Product_Usage_Creation_Triggers'.toLowerCase(), false);

        Account a1 = new Account(Name='Test Account 1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = testKPUs[1].Klaviyo_Account_ID__c);
        Account a2 = new Account(Name='Test Account 2', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = testKPUs[2].Klaviyo_Account_ID__c);
        Account a3 = new Account(Name='Test Account 3', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Experts_Tier__c='Silver', Product_Klaviyo_Account_ID__c = testKPUs[3].Klaviyo_Account_ID__c);
        insert new List <Account> {a1, a2, a3};
    }

    //test methods
    //[RGaokar 1/11/2022 TP #95103 Revised existing test methods to improve code coverage]
    static testMethod void testsetup() {
        Test.startTest();
        SchBatchSyncWithKlaviyoProdUsage.setup();
        Test.stopTest();
    }
    
    //To verify the updates performed by batch apex
    static testMethod void testmanual() {
        Test.startTest();
        SchBatchSyncWithKlaviyoProdUsage.manual();
        Test.stopTest();
        Klaviyo_Product_Usage__c kpu = [SELECT Id, Updated_by_Heroku__c FROM Klaviyo_Product_Usage__c where Klaviyo_Account_ID__c = 'TestKPU0' limit 1];
        Account acc = [Select id, PRODUCT_Ecommerce_Integration__c,PRODUCT_Num_Emailable_Profiles__c,PRODUCT_Stripe_Net_MRR__c from Account limit 1];
        Lead l = [Select id, PRODUCT_Ecommerce_Integration__c, PRODUCT_of_Emailable_Profiles__c from Lead limit 1];
        
        system.assertEquals(false, kpu.Updated_By_Heroku__c);
        system.assertEquals('shopify', acc.PRODUCT_Ecommerce_Integration__c);
        system.assertEquals(100, acc.PRODUCT_Stripe_Net_MRR__c);
        system.assertEquals(3000, acc.PRODUCT_Num_Emailable_Profiles__c);
        system.assertEquals('shopify', l.PRODUCT_Ecommerce_Integration__c);
        system.assertEquals(3000, l.PRODUCT_of_Emailable_Profiles__c);  
    }

}