force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transfer_to_Core_Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Transfer_to_Core_Placeholder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transfer to Core Placeholder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transfer_to_Spec_Ops_Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Transfer_to_Spec_Ops_Placeholder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transfer to Spec Ops Placeholder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTransferToPlaceholderBatchTest.cls
@isTest
private class AccountTransferToPlaceholderBatchTest
{

    @testSetup static void buildData()
    {

        Account a = new Account(Name='Test Account 1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1212', Transfer_to_Spec_Ops_Placeholder__c  = True, Transfer_to_Core_Placeholder__c = true);
        a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Klaviyo Account').getRecordTypeId(); 
        a.FINANCE_Payment_Method__c = 'Stripe'; 
        insert a;
        
        Lead l = new Lead(FirstName = 'Test', LastName = 'Test Last name', Account__c = a.Id, Company = 'Test Company');
        insert l;
        
    }

    @isTest
    private static void testAccountTransferToPlaceholder(){
        
        List <Account> lstAccounts = [select Id from Account order by Name]; 
        List <Lead> lstLeads = [select Id, isConverted from Lead order by Name]; 
        Set<Id> acctIds = new Set<Id>();
        Set<Id> leadIds = new Set<Id>();
        
        for(Account a : lstAccounts){
            acctIds.add(a.Id);
        }
        
        for(Lead l : lstLeads){
            if(!l.isConverted)
                {
                    leadIds.add(l.Id);
                }
        }
        
        Test.StartTest();
        Database.executeBatch(new AccountTransferToPlaceholderBatch(leadIds, acctIds, acctIds), 10);
        Test.StopTest();  
    }

}