force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountClaimProcessLeadsTest.cls
@isTest
private class AccountClaimProcessLeadsTest
{

    @isTest
    private static void testAccountClaimProcessLeads(){
    
        
        Account a = new Account(Name='Test Account 1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1212', OwnerId = System.Label.Core_Placeholder_Id);
        a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Klaviyo Account').getRecordTypeId(); 
        a.FINANCE_Payment_Method__c = 'Stripe'; 
        
        insert a;
        
        // [01/11/2023 vrajapatuni SFDC #1514] Move Inbound leads to Inbound placeholder test cases update
        Lead l1 = new Lead(FirstName = 'Test1', LastName = 'Test Last name 1', Account__c = a.Id, Company = 'Test Company', MARKETING_Initial_Lead_Source__c = 'Inbound', MARKETING_Initial_Lead_Source_Detail__c = 'Direct');
        Lead l2 = new Lead(FirstName = 'Test2', LastName = 'Test Last name 2', Account__c = a.Id, Company = 'Test Company', HasOptedOutOfEmail = True);
        insert new List <Lead> {l1,l2};
        
        AccountClaimProcessLeads.UpdateAccountCliamProcessLeads(new List<ID> {a.Id});
           
    }

}