force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MRRCalc__c.field-meta.xml
<CustomField>
    <fullName>MRRCalc__c</fullName>
    <inlineHelpText>The sum of all Closed Won Opportunity MRR associated with this SF account.</inlineHelpText>
    <label>MRR</label>
    <summarizedField>Opportunity.MRR__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Type__c</field>
        <operation>notEqual</operation>
        <value>Initial Transaction, Subsequent Transaction</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/AlexaRankSchedulerTest.cls
@isTest
private class AlexaRankSchedulerTest
{
    @isTest
    static void testManualRunWithOverride(){
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new SingleRequestMock());
        // Test with manual override query
        List<String> querySelect = new List<String>{'Id','Website'};
        String queryFrom = 'Account';
        String queryWhere = 'Website != \'\' AND MRRCalc__c = 0 AND RecordTypeId = \'012d0000001YZJK\' AND FINANCE_Payment_Method__c = \'Stripe\' LIMIT 1';
        AlexaRankScheduler alexaClientWithQuery = new AlexaRankScheduler(
            querySelect,
            queryFrom,
            queryWhere
        );
        alexaClientWithQuery.manualRun();
    }

    @isTest
    static void testManualRunWithoutOverride(){
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new SingleRequestMock());
        // Test without manual override query
        AlexaRankScheduler alexaClientWithoutQuery = new AlexaRankScheduler();
        alexaClientWithoutQuery.manualRun();
        Test.StopTest();
    }

    @isTest
    static void testScheduledRunWithOverride(){
        String providedCronJobName =  'Periodic Bulk Alexa Rank Fetch test';

        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new SingleRequestMock());
        // Test with manual override query
        String soqlQuery = 'SELECT Id,Website FROM Account WHERE Website != \'\' AND MRRCalc__c = 0 AND RecordTypeId = \'012d0000001YZJK\' AND FINANCE_Payment_Method__c = \'Stripe\' LIMIT 1';

        List<String> querySelect = new List<String>{'Id','Website'};
        String queryFrom = 'Account';
        String queryWhere = 'Website != \'\' AND MRRCalc__c = 0 AND RecordTypeId = \'012d0000001YZJK\' AND FINANCE_Payment_Method__c = \'Stripe\' LIMIT 1';
        System.schedule(providedCronJobName, '0 0 0 ? * SUN#2 *', new AlexaRankScheduler(
            querySelect,
            queryFrom,
            queryWhere
        ));

        GeneralUtils.clearPreviousJob(providedCronJobName);

    }

    @isTest
    static void testScheduledRunWithoutOverride(){
        String providedCronJobName =  'Periodic Bulk Alexa Rank Fetch test';
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new SingleRequestMock());
        // Test without manual override query
        System.schedule(providedCronJobName, '0 0 0 ? * SUN#2 *', new AlexaRankScheduler());
        GeneralUtils.clearPreviousJob(providedCronJobName);
        Test.StopTest();
    }

    // #########################################################################
    // Some utility methods and classes.

    // Class for mocking HTTP callouts
    private class SingleRequestMock implements HttpCalloutMock {
        // Create a mock for HTTP responses from callouts.
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setBody('{}');
            System.debug('=== Making Mock HTTP Callout ===');
            return res;
        }
    }

}