force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MRRCalc__c.field-meta.xml
<CustomField>
    <fullName>MRRCalc__c</fullName>
    <inlineHelpText>The sum of all Closed Won Opportunity MRR associated with this SF account.</inlineHelpText>
    <label>MRR</label>
    <summarizedField>Opportunity.MRR__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Type__c</field>
        <operation>notEqual</operation>
        <value>Initial Transaction, Subsequent Transaction</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/RU_of_Open_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>RU_of_Open_Opportunities__c</fullName>
    <inlineHelpText>Number of Open Opportunities associated with this Account. Calculated with the Rollup COUNT field.</inlineHelpText>
    <label># of Open Opportunities</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>&lt;NEEDS RESOLUTION&gt;, Sales Accepted Opportunity, Best Case, Most Likely, Commit, Not Forecastable Opportunity</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Closed Won, Closed Lost, Closed Won - Needs Review</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Opportunity_Product__c</field>
        <operation>notEqual</operation>
        <value>Toll Free Number Subscription, Complimentary Long Number Subscription, Long Number Subscription, Short Code Subscription, Short Code Throughput Increase Subscription, Toll Free Number Throughput Increase Subscription, SMS Funds</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/AssociatedAccountsCalculation.cls
public class AssociatedAccountsCalculation{

        
    public static void updateAssociatedAccounts(List<Account> accRecs, Map<Id,Account> oldMap){
        
        Set<Id> userIds = new Set<id>();  
 
        /* Gathering all the users that are involved in the update i.e new owner and/or old owner of account into the userIds set. */ 
        if(Trigger.isInsert || Trigger.isUndelete || Trigger.isUpdate){     
             
            for(Account a : accRecs){            
                 
                if(a.OwnerId <> '0050V000006jiOvQAI'){
          
                    Account oldAcc = oldMap.get(a.Id);
                     
                    if(Trigger.isInsert || Trigger.isUnDelete || 
                        (Trigger.isUpdate && 
                            (a.OwnerId <> oldAcc.OwnerId || a.RecordTypeId <> oldAcc.RecordTypeId || a.FINANCE_Payment_Method__c <> oldAcc.FINANCE_Payment_Method__c || a.MRRCalc__c <> oldAcc.MRRCalc__c || a.RU_of_Open_Opportunities__c <> oldAcc.RU_of_Open_Opportunities__c )
                        )
                    ){  
                        userIds.add(a.OwnerId);
                        if(Trigger.isUpdate && oldAcc.OwnerId <> '0050V000006jiOvQAI')
                            userIds.add(oldAcc.OwnerId);
                     }                                          
                }
            }  
        } 
        
        if(Trigger.isDelete){
             for(Account a : accRecs){
                 if(a.OwnerId <> '0050V000006jiOvQAI'){ userIds.add(a.OwnerId); }
             }
         }  
 
        /* By this point, we have gathered all the users that are involved in the update i.e new owner and old owner of account into the userIds set. */
        if(!userIds.isEmpty() && !System.isBatch() && !System.isFuture()){
        
            Database.executeBatch(new UpdateAssociatedAccountsBatch(userIds), 1);
                    
        } 
    }
    
}