force-app/main/default/objects/Account/fields/FINANCE_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FINANCE_Payment_Method__c</fullName>
    <label>Klaviyo Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Klaviyo_Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Master_Account_Id__c</fullName>
    <description>This is used for account de-deuplication</description>
    <label>Master Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountDeduplicationCleanBatchTest.cls
@isTest
private class AccountDeduplicationCleanBatchTest
{

    @testSetup static void buildData()
    {

        Account a1 = new Account(Name='Test Account Special1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Master_Account_Id__c = '12345',  Product_Klaviyo_Account_ID__c = '11032021', website = 'www.klaviyo.com', FINANCE_Payment_Method__c = 'Wire Transfer / Manual Billing', ParentId = null, RecordTypeId = System.label.Klaviyo_Account_Record_Id);
        Account a2 = new Account(Name='Test Account NotSpecial1', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Master_Account_Id__c = '12345', Product_Klaviyo_Account_ID__c = null, website = 'www.klaviyo.com', FINANCE_Payment_Method__c = 'Stripe', ParentId = null, RecordTypeId = System.label.Klaviyo_Account_Record_Id);
        insert new List <Account> {a1, a2};        
        
    }
   
    @isTest
    private static void testAccountDeduplicationCleanBatch(){
        
        List <Account> lstAccounts = [select Id, Name, Master_Account_Id__c from Account order by Name]; 
        
        Test.StartTest();
        AccountDeduplicationCleanBatch obj2 = new AccountDeduplicationCleanBatch();
        Database.QueryLocator ql = obj2.start(null);
        obj2.execute(null, lstAccounts);
        obj2.Finish(null);
        Test.stopTest();  
                   
    }

}