force-app/main/default/objects/Account/fields/Klaviyo_Product_Usage__c.field-meta.xml
<CustomField>
    <fullName>Klaviyo_Product_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Klaviyo Store</label>
    <referenceTo>Klaviyo_Product_Usage__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/KPU_Aggregated_Ecommerce_Platform__c.field-meta.xml
<CustomField>
    <fullName>KPU_Aggregated_Ecommerce_Platform__c</fullName>
    <description>Partner Ecommerce platform.
The value is populated from Aggregated Ecommerce Platform field (bi_Aggregated_Ecommerce_Platform__c) of KPU object record</description>
    <label>KPU: Aggregated Ecommerce Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shopify</fullName>
            </value>
            <value>
                <fullName>Platform not known</fullName>
            </value>
            <value>
                <fullName>Shopify Plus</fullName>
            </value>
            <value>
                <fullName>WooCommerce</fullName>
            </value>
            <value>
                <fullName>BigCommerce</fullName>
            </value>
            <value>
                <fullName>Magento</fullName>
            </value>
            <value>
                <fullName>Salesforce Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>API Integration</fullName>
            </value>
            <value>
                <fullName>Long Tail</fullName>
            </value>
            <value>
                <fullName>PrestaShop</fullName>
            </value>
            <value>
                <fullName>WIX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KPUAggregatedEcommPlatformUpdateBatch.cls
public class KPUAggregatedEcommPlatformUpdateBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String Query = 'Select id, Klaviyo_Product_Usage__r.bi_Aggregated_Ecommerce_Platform__c from Account'; 
        Query += ' where Klaviyo_Product_Usage__c != null AND KPU_Aggregated_Ecommerce_Platform__c = null AND Klaviyo_Product_Usage__r.bi_Aggregated_Ecommerce_Platform__c != null';
        return Database.getQueryLocator(Query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope){
        List<Account> updateAccList = new List<Account>();
        for (Account a:(List<Account>)scope){
            a.KPU_Aggregated_Ecommerce_Platform__c = a.Klaviyo_Product_Usage__r.bi_Aggregated_Ecommerce_Platform__c;
            updateAccList.add(a);
        }
        
        try{
            if(updateAccList.size()>0){
                update updateAccList;
            }     
        }catch(Exception ex){
            List <String> executionFlow = new List <String> ();
            executionFlow.add('Error occured for KPUAggregatedEcommPlatformUpdateBatch Update');
            ExceptionHandling.performExceptionHandling(ex, 'KPUAggregatedEcommPlatformUpdateBatch', executionFlow);  
        }
   
    }
    
    public void finish(Database.BatchableContext bc){
        
    }

}