force-app/main/default/objects/Account/fields/Klaviyo_Product_Usage__c.field-meta.xml
<CustomField>
    <fullName>Klaviyo_Product_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Klaviyo Store</label>
    <referenceTo>Klaviyo_Product_Usage__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/KPU_Aggregated_Ecommerce_Platform__c.field-meta.xml
<CustomField>
    <fullName>KPU_Aggregated_Ecommerce_Platform__c</fullName>
    <description>Partner Ecommerce platform.
The value is populated from Aggregated Ecommerce Platform field (bi_Aggregated_Ecommerce_Platform__c) of KPU object record</description>
    <label>KPU: Aggregated Ecommerce Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shopify</fullName>
            </value>
            <value>
                <fullName>Platform not known</fullName>
            </value>
            <value>
                <fullName>Shopify Plus</fullName>
            </value>
            <value>
                <fullName>WooCommerce</fullName>
            </value>
            <value>
                <fullName>BigCommerce</fullName>
            </value>
            <value>
                <fullName>Magento</fullName>
            </value>
            <value>
                <fullName>Salesforce Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>API Integration</fullName>
            </value>
            <value>
                <fullName>Long Tail</fullName>
            </value>
            <value>
                <fullName>PrestaShop</fullName>
            </value>
            <value>
                <fullName>WIX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KPUAggregatedEcommPlatformBatchTest.cls
@isTest
private class KPUAggregatedEcommPlatformBatchTest {
  @isTest
    private static void testKPUAggregatedEcommPlatformUpdateBatch(){
        //Create Klaviyo Product Usage records
        List<Klaviyo_Product_Usage__c> testKPUs = new List<Klaviyo_Product_Usage__c>();
        for(Integer i=0;i<50;i++) {
            testKPUs.add(new Klaviyo_Product_Usage__c(Klaviyo_Account_ID__c = 'TestKPU'+i, 
                                                      bi_Aggregated_Ecommerce_Platform__c = 'Shopify'));
        }
        insert testKPUs;
        
        //Create Account records
        List<Account> testAccounts = new List<Account>();
        for(integer i =0; i<50; i++){
            testAccounts.add(new Account(Name = 'Test'+ i, Klaviyo_Product_Usage__c = testKPUs[i].id));
        }
        
        insert testAccounts;
        
        Test.startTest();
        KPUAggregatedEcommPlatformUpdateBatch aggEcommBatch = new KPUAggregatedEcommPlatformUpdateBatch();
        Database.executeBatch(aggEcommBatch, 50);
        Test.stopTest();
        Account testAcc = [Select id,KPU_Aggregated_Ecommerce_Platform__c from Account where Name = 'Test0'];
        system.assertEquals('Shopify', testAcc.KPU_Aggregated_Ecommerce_Platform__c);
    }

}