force-app/main/default/objects/Account/fields/MRRCalc__c.field-meta.xml
<CustomField>
    <fullName>MRRCalc__c</fullName>
    <inlineHelpText>The sum of all Closed Won Opportunity MRR associated with this SF account.</inlineHelpText>
    <label>MRR</label>
    <summarizedField>Opportunity.MRR__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Type__c</field>
        <operation>notEqual</operation>
        <value>Initial Transaction, Subsequent Transaction</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_MRR_of_Child_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Total_MRR_of_Child_Accounts__c</fullName>
    <description>Rollup field of all child account MRR</description>
    <inlineHelpText>Total MRR from all children accounts, if any.</inlineHelpText>
    <label>Total MRR of Child Accounts</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountMRRRollUpUpdateQueueableTest.cls
@isTest
private class AccountMRRRollUpUpdateQueueableTest
{

    @isTest
    private static void testAccountMRRRollUpUpdateQueueable(){
    
        Set<Id> accIdsList = new Set<Id>();
        List<Account> accList = new List<Account>();
        Account a1 = new Account(Name='Parent', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1212', Type = 'Parent Account');
        insert a1;
        
        Account a2 = new Account(Name='Child', SUPPORT_Account_Manager__c=UserInfo.getUserId(), ParentId = a1.id);
        insert a2;
        
        accIdsList.add(a1.Id);
        accIdsList.add(a2.Id);
        accList.add(a1);
        accList.add(a2);
        
        Test.StartTest();
        
        List<Account> listOfAccountForBatchOrEnque = [Select Id, Total_MRR_of_Child_Accounts__c, MRRCalc__c From Account Where Id In: accIdsList order by ParentId];
        System.enqueueJob(new AccountMRRRollUpUpdateQueueable(accIdsList, listOfAccountForBatchOrEnque));
        
        Test.stopTest();  
                   
    }

}