force-app/main/default/objects/Account/fields/Product_Klaviyo_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Klaviyo_Account_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The ID (and also public API key) of the account in Klaviyo’s database</inlineHelpText>
    <label>Klaviyo Account ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SUPPORT_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>SUPPORT_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>THIS FIELD HAS HISTORY TRACKING APPLIED - DO NOT REMOVE HISTORY TRACKING.
This field is used by Data Engineering in assessing who the month_start_csm and month_end_csm was at the month start and month end respectively for an account. Do not disable tracking on this field without first checking with Padrig Tuck and Evan Cover as it has direct implications in determining variable compensation for the CSM organization.</description>
    <inlineHelpText>The assigned Account Manager for the related Klaviyo account.</inlineHelpText>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accountmanager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountMRRRollUpBulkUpdateBatchTest.cls
@isTest
private class AccountMRRRollUpBulkUpdateBatchTest
{

    @isTest
    private static void testAccountMRRRollUpBulkUpdateBatch(){
    
        List<Account> accList = new List<Account>();
        Account a1 = new Account(Name='Parent', SUPPORT_Account_Manager__c=UserInfo.getUserId(), Product_Klaviyo_Account_ID__c = '1212', Type = 'Parent Account');
        insert a1;
        
        Account a2 = new Account(Name='Child', SUPPORT_Account_Manager__c=UserInfo.getUserId(), ParentId = a1.id);
        insert a2;
        
        accList.add(a1);
        accList.add(a2);
        
        Test.StartTest();
        
        AccountMRRRollUpBulkUpdateBatch obj = new AccountMRRRollUpBulkUpdateBatch();
        Database.QueryLocator ql = obj.start(null);
        obj.execute(null, accList);
        obj.Finish(null);
        
        Test.stopTest();  
                   
    }

}